services:
  db:
    image: postgres:16-alpine
    container_name: uni_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: ../deploy/backend.Dockerfile
    container_name: uni_backend
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../deploy/frontend.Dockerfile
    container_name: uni_frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
